### ISSUE TITLE
More notes on class initialization

### ISSUE THREAD

**Issue by borkdude** [clj-easy/graal-docs#53]
https://github.com/lread/clj-graal-docs#class-initialization

See https://github.com/oracle/graal/discussions/3476

From Graal 22 on, the global `--initialize-at-build-time` option will be deprecated. 

It is possible to get a list of Clojure-produced packages with something like:

```
(require 'babashka.main)
(->> (map ns-name (all-ns)) (remove #(str/starts-with? % "clojure")) (map #(str/split (str %) #"\.")) (keep butlast) (map #(str/join "." %)) distinct (map munge) (cons "clojure"))
``` 

and then make a comma separated list out of that:

```
"--initialize-at-build-time=clojure,sci.impl,selmer,babashka.nrepl,babashka.impl.clojure.java,babashka.impl,rewrite_clj.node,bencode,rewrite_clj.parser,babashka.impl.clojure,org.httpkit,rewrite_clj.custom_zipper,rewrite_clj.zip,borkdude.graal,babashka.nrepl.impl,babashka.pods,cognitect,babashka,edamame.impl,cheshire,rewrite_clj,hiccup,sci,borkdude,flatland.ordered,babashka.pods.impl,clj_yaml,babashka.impl.clojure.core,datascript,hf.depstar,babashka.impl.tools,sci.addons,babashka.impl.clojure.test"
```

This has an additional benefit that not all Java classes are initialized at build time, reducing the chance on any incorrect behavior.

**Comment by borkdude** [comment]
I'm planning to make a library out of this. Perhaps we can use the Graal annotations processor to accomplish this goal, so then users would only have to include a library on their classpath.

**Comment by borkdude** [comment]
Relevant APIs: 

- https://docs.oracle.com/en/graalvm/enterprise/21/sdk/org/graalvm/nativeimage/hosted/RuntimeClassInitialization.html
-

**Comment by borkdude** [comment]
@ericdallo Made a repo here where we can implement this:

https://github.com/clj-easy/graal-build-time

**Comment by borkdude** [comment]
I guess we can start recommending https://github.com/clj-easy/graal-build-time over the global `--initialize-at-build-time` option now.

**Comment by lread** [comment]
Note to self: warning output from GraalVM 21.2.0
```
--initialize-at-build-time without arguments has been deprecated and will be removed in GraalVM 22.0.
```
